name: Go Sec

on:
  push:
    branches:
      - main

jobs:
  sast-check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Download Go modules
        if: ${{ !env.ACT }}  # Only run if NOT running in act
        run: go mod download

      - name: Verify Go modules
        if: ${{ !env.ACT }}  # Only run if NOT running in act
        run: go mod verify

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.21.4
        with:
          args: ' -fmt=html -out=gosec-report.html ./...'
